//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.7905
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DSServer.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DSServer.xsd", IsNullable=false)]
public partial class DSServer {

    private DSServerAddons[] addonsField;

    [XmlIgnore]
    public string addonUri;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Addons")]
    public DSServerAddons[] Addons {
        get {
            return this.addonsField;
        }
        set {
            this.addonsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DSServer.xsd")]
public partial class DSServerAddons {
    
    private string md5Field;
    
    private string pathField;
    
    private string pboField;
    
    private long sizeField;
    
    private string urlField;
    
    public DSServerAddons() {
        this.md5Field = "";
        this.pathField = "";
        this.pboField = "";
        this.sizeField = ((long)(0));
        this.urlField = "";
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute("")]
    public string Md5 {
        get {
            return this.md5Field;
        }
        set {
            this.md5Field = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute("")]
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute("")]
    public string Pbo {
        get {
            return this.pboField;
        }
        set {
            this.pboField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
    public long Size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute("")]
    public string Url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
}
